# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snitch < Formula
  desc "Catch Cursor agent lies in prose — local lie detector"
  homepage "https://github.com/fristovic/snitch"
  version "0.1.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/fristovic/snitch/releases/download/v0.1.2/snitch_0.1.2_darwin_amd64.tar.gz"
    sha256 "08057d05278454546282ce45d8d8f33a195d0083fd6401d18767554b629ab4c5"

    define_method(:install) do
      bin.install "snitch"
      bin.install "snitchd"
      prefix.install "Snitch Bar.app"
      (share/"snitch").install "install/macos/com.snitch.menubar.plist"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/fristovic/snitch/releases/download/v0.1.2/snitch_0.1.2_darwin_arm64.tar.gz"
    sha256 "ad84d3a4a090ff6a9bd4a5b650c6209812e7ddcdbeeb19c291589b16c600f1e9"

    define_method(:install) do
      bin.install "snitch"
      bin.install "snitchd"
      prefix.install "Snitch Bar.app"
      (share/"snitch").install "install/macos/com.snitch.menubar.plist"
    end
  end

  def post_install
    home = Dir.home
    daemon_plist = File.join(home, "Library/LaunchAgents/com.snitch.daemon.plist")
    if File.exist?(daemon_plist)
      system "launchctl", "bootout", "gui/#{Process.uid}/com.snitch.daemon" rescue nil
      File.delete(daemon_plist)
    end
    app_path = File.join(opt_prefix, "Snitch Bar.app")
    plist_src = File.join(share, "snitch", "com.snitch.menubar.plist")
    plist_dest = File.join(home, "Library/LaunchAgents/com.snitch.menubar.plist")
    if File.exist?(plist_src) && File.directory?(app_path)
      content = File.read(plist_src).gsub("__SNITCHBAR_APP__", app_path).gsub("__HOME__", home)
      FileUtils.mkdir_p(File.dirname(plist_dest))
      File.write(plist_dest, content)
      system "launchctl", "bootout", "gui/#{Process.uid}/com.snitch.menubar" rescue nil
      system "launchctl", "bootstrap", "gui/#{Process.uid}", plist_dest rescue system("launchctl", "load", plist_dest)
    end
  end

  def caveats
    <<~EOS
      Snitch Bar manages lie detection automatically.
      After install:
        snitch start
      Use Start Snitching / Stop Snitching in the menu bar to pause or resume.
      No brew services step — the menubar LaunchAgent opens Snitch Bar at login.
    EOS
  end
end
