# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snitch < Formula
  desc "Deterministic prose claim verifier for AI coding agents (Cursor, Claude Code, Codex, Pi, OpenCode)"
  homepage "https://github.com/fristovic/snitch"
  version "0.5.0"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/fristovic/snitch/releases/download/v0.5.0/snitch_0.5.0_darwin_amd64.tar.gz"
    sha256 "a4a5c77fe1e707205807a9d7e72e67d6cc48adcac25d01b301b293cc725d1c96"

    define_method(:install) do
      bin.install "snitch"
      bin.install "snitchd"
      if File.directory?("Snitch Bar.app")
        prefix.install "Snitch Bar.app"
      elsif File.directory?("Contents")
        (prefix/"Snitch Bar.app").install "Contents"
      else
        system buildpath/"scripts/bundle-snitchbar.sh", buildpath/"snitchbar", version, buildpath/"snitchd"
        prefix.install "Snitch Bar.app"
      end
      (share/"snitch").install "install/macos/com.snitch.menubar.plist"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/fristovic/snitch/releases/download/v0.5.0/snitch_0.5.0_darwin_arm64.tar.gz"
    sha256 "7c9aa49167089de3d827e2758a061f728b491e8a7e218cfec5911d3a78f4ac17"

    define_method(:install) do
      bin.install "snitch"
      bin.install "snitchd"
      if File.directory?("Snitch Bar.app")
        prefix.install "Snitch Bar.app"
      elsif File.directory?("Contents")
        (prefix/"Snitch Bar.app").install "Contents"
      else
        system buildpath/"scripts/bundle-snitchbar.sh", buildpath/"snitchbar", version, buildpath/"snitchd"
        prefix.install "Snitch Bar.app"
      end
      (share/"snitch").install "install/macos/com.snitch.menubar.plist"
    end
  end

  def post_install
    home = Dir.home
    daemon_plist = File.join(home, "Library/LaunchAgents/com.snitch.daemon.plist")
    if File.exist?(daemon_plist)
      system "launchctl", "bootout", "gui/#{Process.uid}/com.snitch.daemon" rescue nil
      File.delete(daemon_plist)
    end
    app_path = File.join(opt_prefix, "Snitch Bar.app")
    contents = File.join(app_path, "Contents")
    unless File.directory?(File.join(contents, "MacOS"))
      %w[MacOS Resources Info.plist].each do |name|
        src = File.join(app_path, name)
        FileUtils.mkdir_p(contents)
        FileUtils.mv(src, File.join(contents, name)) if File.exist?(src)
      end
    end
    plist_src = File.join(share, "snitch", "com.snitch.menubar.plist")
    plist_dest = File.join(home, "Library/LaunchAgents/com.snitch.menubar.plist")
    if File.exist?(plist_src) && File.directory?(app_path)
      content = File.read(plist_src).gsub("__SNITCHBAR_APP__", app_path).gsub("__HOME__", home)
      FileUtils.mkdir_p(File.dirname(plist_dest))
      File.write(plist_dest, content)
      system "launchctl", "bootout", "gui/#{Process.uid}/com.snitch.menubar" rescue nil
      system "launchctl", "bootstrap", "gui/#{Process.uid}", plist_dest rescue system("launchctl", "load", plist_dest)
    end
  end

  def caveats
    <<~EOS
      Snitch Bar manages claim verification automatically.
      After install:
        snitch start
      Use Start Snitching / Stop Snitching in the menu bar to pause or resume.
      No brew services step — the menubar LaunchAgent opens Snitch Bar at login.
    EOS
  end
end
